### ISSUE TITLE
SASInterstitialView.h not found

### ISSUE THREAD

**Issue by francocorreasosa** [appsfire/Appsfire-iOS-SDK#2]
```
Lexical or preprocessor issue:
    SASInterstitialView.h not found
```
Please, help me :(

**Comment by alikaragoz** [comment]
Hello @francocorreasosa, can you please give us a little bit more information and context ?
As I see it, you are using mediation but forgot the include the Smart Ad Server SDK.
Thank you.

**Comment by francocorreasosa** [comment]
Just fixed it, I just restarted Xcode.

Thanks anyway.
