### ISSUE TITLE
AppsfireAdSDKDelegate does not have a protocol method for querying the controller that will host the Store Kit

### ISSUE THREAD

**Issue by nomadplanet** [appsfire/Appsfire-iOS-SDK#3]
In AppsfireAdSDK v2.6.0, the old method for getting sashimis are now deprecated.

For instance:
```objc
+ (AFAdSDKSashimiView *)sashimiViewForNibName:(NSString *)nibName withController:(UIViewController *)controller andError:(NSError **)error __deprecated_msg("We're now asking for the controller (that will host the Store Kit) via `AppsfireAdSDKDelegate`");
```

But in the AppsfireAdSDKDelegate protocol there is no method for querying that controller.

**Comment by Vinzius** [comment]
Hi !

My bad, it's in the protocol `AFAdSDKSashimiViewDelegate` (delegate of the sashimi view). I'll update the message in the header file.

Thanks!
